### ISSUE TITLE
IndexOutOfBoundsException on rendering spec in IDEA 15

### ISSUE THREAD

**Issue by adam-dabrowski** [concordion/idea-concordion-support#8]
```
Index: 2, Size: 2
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.concordion.plugin.idea.ConcordionPsiUtils.argumentTypesMatchParameterTypes(ConcordionPsiUtils.java:97)
	at org.concordion.plugin.idea.ConcordionPsiUtils.lambda$findMethodInClass$3(ConcordionPsiUtils.java:85)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.concordion.plugin.idea.ConcordionPsiUtils.findMethodInClass(ConcordionPsiUtils.java:87)
	at org.concordion.plugin.idea.lang.psi.ConcordionMethodInternalImpl.determineContainingMember(ConcordionMethodInternalImpl.java:32)
	at org.concordion.plugin.idea.lang.psi.ConcordionMethodInternalImpl.determineContainingMember(ConcordionMethodInternalImpl.java:13)
	at org.concordion.plugin.idea.PsiElementCache.getOrCompute(PsiElementCache.java:50)
	at org.concordion.plugin.idea.lang.psi.AbstractConcordionMember.getContainingMember(AbstractConcordionMember.java:31)
	at org.concordion.plugin.idea.lang.psi.ConcordionMethodInternalImpl.isResolvable(ConcordionMethodInternalImpl.java:21)
	at org.concordion.plugin.idea.ConcordionExpressionElementPattern$1.accepts(ConcordionExpressionElementPattern.java:18)
	at org.concordion.plugin.idea.ConcordionExpressionElementPattern$1.accepts(ConcordionExpressionElementPattern.java:15)
	at com.intellij.patterns.ElementPatternCondition.accepts(ElementPatternCondition.java:55)
	at com.intellij.patterns.ObjectPattern.accepts(ObjectPattern.java:56)
	at org.concordion.plugin.idea.annotator.UnresolvedMemberAnnotator.annotate(UnresolvedMemberAnnotator.java:28)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:162)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:103)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass$4.run(InjectedGeneralHighlightingPass.java:374)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.a(InjectedGeneralHighlightingPass.java:369)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.a(InjectedGeneralHighlightingPass.java:245)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.access$000(InjectedGeneralHighlightingPass.java:53)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass$3.process(InjectedGeneralHighlightingPass.java:215)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass$3.process(InjectedGeneralHighlightingPass.java:212)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by gmandnepr** [comment]
Hello,

Thanks for reporting. This issue was fixed couple of days ago: https://github.com/concordion/idea-concordion-support/commit/05efe14f30fb3a716b774132755f2f2e93aafc3f

Unfortunately I am not planning to release soon, but you may download attached distribution with this bug fixed.
[IdeaConcordionSupport-20151218.zip](https://github.com/concordion/idea-concordion-support/files/67327/IdeaConcordionSupport-20151218.zip)
